// Export the composed crew as a real, runnable CrewAI project (.zip).
// Same generator output as the live preview, split into project files.

import JSZip from "jszip";
import { FlowState } from "./types";
import { genProjectFiles } from "./codegen";
import { ScheduleConfig, scheduleMarkdown } from "./schedule";

const README = `# Exported CrewAI project

Generated by the Visual Agent Builder.

## Run
1. python -m venv .venv && source .venv/bin/activate   # Windows: .venv\\Scripts\\activate
2. pip install -r requirements.txt
3. cp .env.example .env   # then fill in credentials
4. python main.py
`;

export async function exportProject(
  state: FlowState,
  schedule?: ScheduleConfig | null,
): Promise<void> {
  const zip = new JSZip();
  const files = genProjectFiles(state);
  Object.entries(files).forEach(([name, content]) => zip.file(name, content));
  zip.file("README.md", README);
  if (schedule) zip.file("SCHEDULE.md", scheduleMarkdown(schedule));

  const blob = await zip.generateAsync({ type: "blob" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = "crewai_project.zip";
  a.click();
  URL.revokeObjectURL(url);
}
