"""Writes a `.env` for a materialized project, per CrewAI's "keys in .env"
guidance. Secrets (tool credentials + LLM key) live here, never in generated code.
"""
from __future__ import annotations

import os

import flow_graph
from tools_registry import TOOL_SCHEMA


def env_lines(flow: dict, creds: dict, settings: dict | None = None) -> list[str]:
    """The .env body: LLM keys + exactly the fields the used tools require."""
    settings = settings or {}
    lines = ["# Generated by the Visual Agent Builder live-run backend.", ""]

    # LLM the agents reason with
    lines.append("# --- LLM ---")
    lines.append(f"LLM_MODEL={settings.get('model') or os.environ.get('LLM_MODEL', '')}")
    lines.append(f"LLM_BASE_URL={settings.get('baseUrl') or os.environ.get('LLM_BASE_URL', '')}")
    lines.append(f"LLM_API_KEY={settings.get('apiKey') or os.environ.get('LLM_API_KEY', '')}")
    lines.append("")

    # only the fields the tools on this canvas actually need
    used = flow_graph.used_tool_keys(flow)
    if used:
        lines.append("# --- tool credentials ---")
        for key in used:
            schema = TOOL_SCHEMA.get(key)
            if not schema:
                continue
            for field in schema["fields"]:
                val = creds.get(field) or os.environ.get(field, "")
                lines.append(f"{field}={val}")
        lines.append("")
    return lines


def write_env(path: str, flow: dict, creds: dict, settings: dict | None = None) -> str:
    body = "\n".join(env_lines(flow, creds, settings)) + "\n"
    with open(path, "w", encoding="utf-8") as f:
        f.write(body)
    return path
